//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PegasusKYCPortal.GenericKYCApiLevel1 {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="KYCApiSoap", Namespace="KYCApi")]
    public partial class KYCApi : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UploadDocumentOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApproveDocumentOperationCompleted;
        
        private System.Threading.SendOrPostCallback RejectDocumentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBusinessDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateBusinessOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateDirectorOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllBusinessesOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerifyUserCredentialsOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerifyUserOTPOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateDepartmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateRoleOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDepartmentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRolesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateNationalIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckUserSanctionStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetClientDetailsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public KYCApi() {
            this.Url = "https://localhost:44371/KYCApi.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UploadDocumentCompletedEventHandler UploadDocumentCompleted;
        
        /// <remarks/>
        public event ApproveDocumentCompletedEventHandler ApproveDocumentCompleted;
        
        /// <remarks/>
        public event RejectDocumentCompletedEventHandler RejectDocumentCompleted;
        
        /// <remarks/>
        public event GetBusinessDetailsCompletedEventHandler GetBusinessDetailsCompleted;
        
        /// <remarks/>
        public event CreateBusinessCompletedEventHandler CreateBusinessCompleted;
        
        /// <remarks/>
        public event CreateDirectorCompletedEventHandler CreateDirectorCompleted;
        
        /// <remarks/>
        public event GetAllBusinessesCompletedEventHandler GetAllBusinessesCompleted;
        
        /// <remarks/>
        public event VerifyUserCredentialsCompletedEventHandler VerifyUserCredentialsCompleted;
        
        /// <remarks/>
        public event VerifyUserOTPCompletedEventHandler VerifyUserOTPCompleted;
        
        /// <remarks/>
        public event CreateDepartmentCompletedEventHandler CreateDepartmentCompleted;
        
        /// <remarks/>
        public event CreateRoleCompletedEventHandler CreateRoleCompleted;
        
        /// <remarks/>
        public event CreateUserCompletedEventHandler CreateUserCompleted;
        
        /// <remarks/>
        public event GetDepartmentsCompletedEventHandler GetDepartmentsCompleted;
        
        /// <remarks/>
        public event GetRolesCompletedEventHandler GetRolesCompleted;
        
        /// <remarks/>
        public event GetUsersCompletedEventHandler GetUsersCompleted;
        
        /// <remarks/>
        public event ValidateNationalIdCompletedEventHandler ValidateNationalIdCompleted;
        
        /// <remarks/>
        public event CheckUserSanctionStatusCompletedEventHandler CheckUserSanctionStatusCompleted;
        
        /// <remarks/>
        public event GetClientDetailsCompletedEventHandler GetClientDetailsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("KYCApi/UploadDocument", RequestNamespace="KYCApi", ResponseNamespace="KYCApi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public APIResponse UploadDocument(string registrationNumber, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] documentData, string documentName, string documentType, int businessID) {
            object[] results = this.Invoke("UploadDocument", new object[] {
                        registrationNumber,
                        documentData,
                        documentName,
                        documentType,
                        businessID});
            return ((APIResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UploadDocumentAsync(string registrationNumber, byte[] documentData, string documentName, string documentType, int businessID) {
            this.UploadDocumentAsync(registrationNumber, documentData, documentName, documentType, businessID, null);
        }
        
        /// <remarks/>
        public void UploadDocumentAsync(string registrationNumber, byte[] documentData, string documentName, string documentType, int businessID, object userState) {
            if ((this.UploadDocumentOperationCompleted == null)) {
                this.UploadDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadDocumentOperationCompleted);
            }
            this.InvokeAsync("UploadDocument", new object[] {
                        registrationNumber,
                        documentData,
                        documentName,
                        documentType,
                        businessID}, this.UploadDocumentOperationCompleted, userState);
        }
        
        private void OnUploadDocumentOperationCompleted(object arg) {
            if ((this.UploadDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadDocumentCompleted(this, new UploadDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("KYCApi/ApproveDocument", RequestNamespace="KYCApi", ResponseNamespace="KYCApi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public APIResponse ApproveDocument(int documentId) {
            object[] results = this.Invoke("ApproveDocument", new object[] {
                        documentId});
            return ((APIResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ApproveDocumentAsync(int documentId) {
            this.ApproveDocumentAsync(documentId, null);
        }
        
        /// <remarks/>
        public void ApproveDocumentAsync(int documentId, object userState) {
            if ((this.ApproveDocumentOperationCompleted == null)) {
                this.ApproveDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApproveDocumentOperationCompleted);
            }
            this.InvokeAsync("ApproveDocument", new object[] {
                        documentId}, this.ApproveDocumentOperationCompleted, userState);
        }
        
        private void OnApproveDocumentOperationCompleted(object arg) {
            if ((this.ApproveDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApproveDocumentCompleted(this, new ApproveDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("KYCApi/RejectDocument", RequestNamespace="KYCApi", ResponseNamespace="KYCApi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public APIResponse RejectDocument(int documentId) {
            object[] results = this.Invoke("RejectDocument", new object[] {
                        documentId});
            return ((APIResponse)(results[0]));
        }
        
        /// <remarks/>
        public void RejectDocumentAsync(int documentId) {
            this.RejectDocumentAsync(documentId, null);
        }
        
        /// <remarks/>
        public void RejectDocumentAsync(int documentId, object userState) {
            if ((this.RejectDocumentOperationCompleted == null)) {
                this.RejectDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRejectDocumentOperationCompleted);
            }
            this.InvokeAsync("RejectDocument", new object[] {
                        documentId}, this.RejectDocumentOperationCompleted, userState);
        }
        
        private void OnRejectDocumentOperationCompleted(object arg) {
            if ((this.RejectDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RejectDocumentCompleted(this, new RejectDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("KYCApi/GetBusinessDetails", RequestNamespace="KYCApi", ResponseNamespace="KYCApi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public APIResponse GetBusinessDetails(string registrationNumber) {
            object[] results = this.Invoke("GetBusinessDetails", new object[] {
                        registrationNumber});
            return ((APIResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetBusinessDetailsAsync(string registrationNumber) {
            this.GetBusinessDetailsAsync(registrationNumber, null);
        }
        
        /// <remarks/>
        public void GetBusinessDetailsAsync(string registrationNumber, object userState) {
            if ((this.GetBusinessDetailsOperationCompleted == null)) {
                this.GetBusinessDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBusinessDetailsOperationCompleted);
            }
            this.InvokeAsync("GetBusinessDetails", new object[] {
                        registrationNumber}, this.GetBusinessDetailsOperationCompleted, userState);
        }
        
        private void OnGetBusinessDetailsOperationCompleted(object arg) {
            if ((this.GetBusinessDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBusinessDetailsCompleted(this, new GetBusinessDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("KYCApi/CreateBusiness", RequestNamespace="KYCApi", ResponseNamespace="KYCApi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CreateBusiness(BusinessDetails businessDetails) {
            object[] results = this.Invoke("CreateBusiness", new object[] {
                        businessDetails});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CreateBusinessAsync(BusinessDetails businessDetails) {
            this.CreateBusinessAsync(businessDetails, null);
        }
        
        /// <remarks/>
        public void CreateBusinessAsync(BusinessDetails businessDetails, object userState) {
            if ((this.CreateBusinessOperationCompleted == null)) {
                this.CreateBusinessOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateBusinessOperationCompleted);
            }
            this.InvokeAsync("CreateBusiness", new object[] {
                        businessDetails}, this.CreateBusinessOperationCompleted, userState);
        }
        
        private void OnCreateBusinessOperationCompleted(object arg) {
            if ((this.CreateBusinessCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateBusinessCompleted(this, new CreateBusinessCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("KYCApi/CreateDirector", RequestNamespace="KYCApi", ResponseNamespace="KYCApi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public APIResponse CreateDirector(Director directorDetails) {
            object[] results = this.Invoke("CreateDirector", new object[] {
                        directorDetails});
            return ((APIResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CreateDirectorAsync(Director directorDetails) {
            this.CreateDirectorAsync(directorDetails, null);
        }
        
        /// <remarks/>
        public void CreateDirectorAsync(Director directorDetails, object userState) {
            if ((this.CreateDirectorOperationCompleted == null)) {
                this.CreateDirectorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateDirectorOperationCompleted);
            }
            this.InvokeAsync("CreateDirector", new object[] {
                        directorDetails}, this.CreateDirectorOperationCompleted, userState);
        }
        
        private void OnCreateDirectorOperationCompleted(object arg) {
            if ((this.CreateDirectorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateDirectorCompleted(this, new CreateDirectorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("KYCApi/GetAllBusinesses", RequestNamespace="KYCApi", ResponseNamespace="KYCApi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public APIResponse GetAllBusinesses() {
            object[] results = this.Invoke("GetAllBusinesses", new object[0]);
            return ((APIResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllBusinessesAsync() {
            this.GetAllBusinessesAsync(null);
        }
        
        /// <remarks/>
        public void GetAllBusinessesAsync(object userState) {
            if ((this.GetAllBusinessesOperationCompleted == null)) {
                this.GetAllBusinessesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllBusinessesOperationCompleted);
            }
            this.InvokeAsync("GetAllBusinesses", new object[0], this.GetAllBusinessesOperationCompleted, userState);
        }
        
        private void OnGetAllBusinessesOperationCompleted(object arg) {
            if ((this.GetAllBusinessesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllBusinessesCompleted(this, new GetAllBusinessesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("KYCApi/VerifyUserCredentials", RequestNamespace="KYCApi", ResponseNamespace="KYCApi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool VerifyUserCredentials(string username, string password, out string email) {
            object[] results = this.Invoke("VerifyUserCredentials", new object[] {
                        username,
                        password});
            email = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void VerifyUserCredentialsAsync(string username, string password) {
            this.VerifyUserCredentialsAsync(username, password, null);
        }
        
        /// <remarks/>
        public void VerifyUserCredentialsAsync(string username, string password, object userState) {
            if ((this.VerifyUserCredentialsOperationCompleted == null)) {
                this.VerifyUserCredentialsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyUserCredentialsOperationCompleted);
            }
            this.InvokeAsync("VerifyUserCredentials", new object[] {
                        username,
                        password}, this.VerifyUserCredentialsOperationCompleted, userState);
        }
        
        private void OnVerifyUserCredentialsOperationCompleted(object arg) {
            if ((this.VerifyUserCredentialsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyUserCredentialsCompleted(this, new VerifyUserCredentialsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("KYCApi/VerifyUserOTP", RequestNamespace="KYCApi", ResponseNamespace="KYCApi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VerifyOTPResponse VerifyUserOTP(string email, string otp) {
            object[] results = this.Invoke("VerifyUserOTP", new object[] {
                        email,
                        otp});
            return ((VerifyOTPResponse)(results[0]));
        }
        
        /// <remarks/>
        public void VerifyUserOTPAsync(string email, string otp) {
            this.VerifyUserOTPAsync(email, otp, null);
        }
        
        /// <remarks/>
        public void VerifyUserOTPAsync(string email, string otp, object userState) {
            if ((this.VerifyUserOTPOperationCompleted == null)) {
                this.VerifyUserOTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyUserOTPOperationCompleted);
            }
            this.InvokeAsync("VerifyUserOTP", new object[] {
                        email,
                        otp}, this.VerifyUserOTPOperationCompleted, userState);
        }
        
        private void OnVerifyUserOTPOperationCompleted(object arg) {
            if ((this.VerifyUserOTPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyUserOTPCompleted(this, new VerifyUserOTPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("KYCApi/CreateDepartment", RequestNamespace="KYCApi", ResponseNamespace="KYCApi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateDepartment(string departmentName, int createdBy) {
            object[] results = this.Invoke("CreateDepartment", new object[] {
                        departmentName,
                        createdBy});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateDepartmentAsync(string departmentName, int createdBy) {
            this.CreateDepartmentAsync(departmentName, createdBy, null);
        }
        
        /// <remarks/>
        public void CreateDepartmentAsync(string departmentName, int createdBy, object userState) {
            if ((this.CreateDepartmentOperationCompleted == null)) {
                this.CreateDepartmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateDepartmentOperationCompleted);
            }
            this.InvokeAsync("CreateDepartment", new object[] {
                        departmentName,
                        createdBy}, this.CreateDepartmentOperationCompleted, userState);
        }
        
        private void OnCreateDepartmentOperationCompleted(object arg) {
            if ((this.CreateDepartmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateDepartmentCompleted(this, new CreateDepartmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("KYCApi/CreateRole", RequestNamespace="KYCApi", ResponseNamespace="KYCApi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateRole(string roleName, string roleDescription, int createdBy, string defaultPage) {
            object[] results = this.Invoke("CreateRole", new object[] {
                        roleName,
                        roleDescription,
                        createdBy,
                        defaultPage});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateRoleAsync(string roleName, string roleDescription, int createdBy, string defaultPage) {
            this.CreateRoleAsync(roleName, roleDescription, createdBy, defaultPage, null);
        }
        
        /// <remarks/>
        public void CreateRoleAsync(string roleName, string roleDescription, int createdBy, string defaultPage, object userState) {
            if ((this.CreateRoleOperationCompleted == null)) {
                this.CreateRoleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateRoleOperationCompleted);
            }
            this.InvokeAsync("CreateRole", new object[] {
                        roleName,
                        roleDescription,
                        createdBy,
                        defaultPage}, this.CreateRoleOperationCompleted, userState);
        }
        
        private void OnCreateRoleOperationCompleted(object arg) {
            if ((this.CreateRoleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateRoleCompleted(this, new CreateRoleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("KYCApi/CreateUser", RequestNamespace="KYCApi", ResponseNamespace="KYCApi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateUser(string firstName, string lastName, string email, string username, int departmentID, int roleID, int createdBy, string password) {
            object[] results = this.Invoke("CreateUser", new object[] {
                        firstName,
                        lastName,
                        email,
                        username,
                        departmentID,
                        roleID,
                        createdBy,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateUserAsync(string firstName, string lastName, string email, string username, int departmentID, int roleID, int createdBy, string password) {
            this.CreateUserAsync(firstName, lastName, email, username, departmentID, roleID, createdBy, password, null);
        }
        
        /// <remarks/>
        public void CreateUserAsync(string firstName, string lastName, string email, string username, int departmentID, int roleID, int createdBy, string password, object userState) {
            if ((this.CreateUserOperationCompleted == null)) {
                this.CreateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateUserOperationCompleted);
            }
            this.InvokeAsync("CreateUser", new object[] {
                        firstName,
                        lastName,
                        email,
                        username,
                        departmentID,
                        roleID,
                        createdBy,
                        password}, this.CreateUserOperationCompleted, userState);
        }
        
        private void OnCreateUserOperationCompleted(object arg) {
            if ((this.CreateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateUserCompleted(this, new CreateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("KYCApi/GetDepartments", RequestNamespace="KYCApi", ResponseNamespace="KYCApi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetDepartments() {
            object[] results = this.Invoke("GetDepartments", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetDepartmentsAsync() {
            this.GetDepartmentsAsync(null);
        }
        
        /// <remarks/>
        public void GetDepartmentsAsync(object userState) {
            if ((this.GetDepartmentsOperationCompleted == null)) {
                this.GetDepartmentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDepartmentsOperationCompleted);
            }
            this.InvokeAsync("GetDepartments", new object[0], this.GetDepartmentsOperationCompleted, userState);
        }
        
        private void OnGetDepartmentsOperationCompleted(object arg) {
            if ((this.GetDepartmentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDepartmentsCompleted(this, new GetDepartmentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("KYCApi/GetRoles", RequestNamespace="KYCApi", ResponseNamespace="KYCApi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetRoles() {
            object[] results = this.Invoke("GetRoles", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetRolesAsync() {
            this.GetRolesAsync(null);
        }
        
        /// <remarks/>
        public void GetRolesAsync(object userState) {
            if ((this.GetRolesOperationCompleted == null)) {
                this.GetRolesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRolesOperationCompleted);
            }
            this.InvokeAsync("GetRoles", new object[0], this.GetRolesOperationCompleted, userState);
        }
        
        private void OnGetRolesOperationCompleted(object arg) {
            if ((this.GetRolesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRolesCompleted(this, new GetRolesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("KYCApi/GetUsers", RequestNamespace="KYCApi", ResponseNamespace="KYCApi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetUsers() {
            object[] results = this.Invoke("GetUsers", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetUsersAsync() {
            this.GetUsersAsync(null);
        }
        
        /// <remarks/>
        public void GetUsersAsync(object userState) {
            if ((this.GetUsersOperationCompleted == null)) {
                this.GetUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsersOperationCompleted);
            }
            this.InvokeAsync("GetUsers", new object[0], this.GetUsersOperationCompleted, userState);
        }
        
        private void OnGetUsersOperationCompleted(object arg) {
            if ((this.GetUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsersCompleted(this, new GetUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("KYCApi/ValidateNationalId", RequestNamespace="KYCApi", ResponseNamespace="KYCApi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public NationalIDValidationResponse ValidateNationalId(string dob, string idNumber, string givenName, string NIN, string surname) {
            object[] results = this.Invoke("ValidateNationalId", new object[] {
                        dob,
                        idNumber,
                        givenName,
                        NIN,
                        surname});
            return ((NationalIDValidationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateNationalIdAsync(string dob, string idNumber, string givenName, string NIN, string surname) {
            this.ValidateNationalIdAsync(dob, idNumber, givenName, NIN, surname, null);
        }
        
        /// <remarks/>
        public void ValidateNationalIdAsync(string dob, string idNumber, string givenName, string NIN, string surname, object userState) {
            if ((this.ValidateNationalIdOperationCompleted == null)) {
                this.ValidateNationalIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateNationalIdOperationCompleted);
            }
            this.InvokeAsync("ValidateNationalId", new object[] {
                        dob,
                        idNumber,
                        givenName,
                        NIN,
                        surname}, this.ValidateNationalIdOperationCompleted, userState);
        }
        
        private void OnValidateNationalIdOperationCompleted(object arg) {
            if ((this.ValidateNationalIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateNationalIdCompleted(this, new ValidateNationalIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("KYCApi/CheckUserSanctionStatus", RequestNamespace="KYCApi", ResponseNamespace="KYCApi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SanctionsResponse CheckUserSanctionStatus(string _name) {
            object[] results = this.Invoke("CheckUserSanctionStatus", new object[] {
                        _name});
            return ((SanctionsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CheckUserSanctionStatusAsync(string _name) {
            this.CheckUserSanctionStatusAsync(_name, null);
        }
        
        /// <remarks/>
        public void CheckUserSanctionStatusAsync(string _name, object userState) {
            if ((this.CheckUserSanctionStatusOperationCompleted == null)) {
                this.CheckUserSanctionStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckUserSanctionStatusOperationCompleted);
            }
            this.InvokeAsync("CheckUserSanctionStatus", new object[] {
                        _name}, this.CheckUserSanctionStatusOperationCompleted, userState);
        }
        
        private void OnCheckUserSanctionStatusOperationCompleted(object arg) {
            if ((this.CheckUserSanctionStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckUserSanctionStatusCompleted(this, new CheckUserSanctionStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("KYCApi/GetClientDetails", RequestNamespace="KYCApi", ResponseNamespace="KYCApi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetClientDetails() {
            object[] results = this.Invoke("GetClientDetails", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetClientDetailsAsync() {
            this.GetClientDetailsAsync(null);
        }
        
        /// <remarks/>
        public void GetClientDetailsAsync(object userState) {
            if ((this.GetClientDetailsOperationCompleted == null)) {
                this.GetClientDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClientDetailsOperationCompleted);
            }
            this.InvokeAsync("GetClientDetails", new object[0], this.GetClientDetailsOperationCompleted, userState);
        }
        
        private void OnGetClientDetailsOperationCompleted(object arg) {
            if ((this.GetClientDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClientDetailsCompleted(this, new GetClientDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="KYCApi")]
    public partial class APIResponse {
        
        private bool successField;
        
        private string messageField;
        
        private object dataField;
        
        private System.Data.DataTable dataTablePropertyField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public object Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataTable DataTableProperty {
            get {
                return this.dataTablePropertyField;
            }
            set {
                this.dataTablePropertyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="KYCApi")]
    public partial class SanctionsResponse {
        
        private string statusCodeField;
        
        private string scoreField;
        
        private bool sanctionedField;
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
        
        /// <remarks/>
        public bool Sanctioned {
            get {
                return this.sanctionedField;
            }
            set {
                this.sanctionedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="KYCApi")]
    public partial class NationalIDValidationResponse {
        
        private string statusCodeField;
        
        private string descriptionField;
        
        private string messageField;
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="KYCApi")]
    public partial class UserDTO {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string emailField;
        
        private int roleIdField;
        
        private int userIdField;
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public int RoleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
            }
        }
        
        /// <remarks/>
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="KYCApi")]
    public partial class VerifyOTPResponse {
        
        private UserDTO userDTOField;
        
        private bool statusField;
        
        private string messageField;
        
        /// <remarks/>
        public UserDTO userDTO {
            get {
                return this.userDTOField;
            }
            set {
                this.userDTOField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="KYCApi")]
    public partial class Director {
        
        private int businessIDField;
        
        private string surnameField;
        
        private string givenNameField;
        
        private string dateOfBirthField;
        
        private string cardNumberField;
        
        private string nINField;
        
        private string sanctionStatusField;
        
        private string niraStatusField;
        
        /// <remarks/>
        public int BusinessID {
            get {
                return this.businessIDField;
            }
            set {
                this.businessIDField = value;
            }
        }
        
        /// <remarks/>
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        public string GivenName {
            get {
                return this.givenNameField;
            }
            set {
                this.givenNameField = value;
            }
        }
        
        /// <remarks/>
        public string DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string CardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
            }
        }
        
        /// <remarks/>
        public string NIN {
            get {
                return this.nINField;
            }
            set {
                this.nINField = value;
            }
        }
        
        /// <remarks/>
        public string SanctionStatus {
            get {
                return this.sanctionStatusField;
            }
            set {
                this.sanctionStatusField = value;
            }
        }
        
        /// <remarks/>
        public string NiraStatus {
            get {
                return this.niraStatusField;
            }
            set {
                this.niraStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="KYCApi")]
    public partial class BusinessDetails {
        
        private string companyNameField;
        
        private string companyRegistrationNumberField;
        
        private string businessTypeField;
        
        private string licenseNoField;
        
        private string tINField;
        
        private string startDateField;
        
        private string addressField;
        
        private string locationProofField;
        
        private string emailField;
        
        private string phoneField;
        
        private string websiteField;
        
        private string mainBusinessActivityField;
        
        private string industryField;
        
        private int yearsInOperationField;
        
        private int numberOfEmployeesField;
        
        private string companyProfileField;
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyRegistrationNumber {
            get {
                return this.companyRegistrationNumberField;
            }
            set {
                this.companyRegistrationNumberField = value;
            }
        }
        
        /// <remarks/>
        public string BusinessType {
            get {
                return this.businessTypeField;
            }
            set {
                this.businessTypeField = value;
            }
        }
        
        /// <remarks/>
        public string LicenseNo {
            get {
                return this.licenseNoField;
            }
            set {
                this.licenseNoField = value;
            }
        }
        
        /// <remarks/>
        public string TIN {
            get {
                return this.tINField;
            }
            set {
                this.tINField = value;
            }
        }
        
        /// <remarks/>
        public string StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string LocationProof {
            get {
                return this.locationProofField;
            }
            set {
                this.locationProofField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Website {
            get {
                return this.websiteField;
            }
            set {
                this.websiteField = value;
            }
        }
        
        /// <remarks/>
        public string MainBusinessActivity {
            get {
                return this.mainBusinessActivityField;
            }
            set {
                this.mainBusinessActivityField = value;
            }
        }
        
        /// <remarks/>
        public string Industry {
            get {
                return this.industryField;
            }
            set {
                this.industryField = value;
            }
        }
        
        /// <remarks/>
        public int YearsInOperation {
            get {
                return this.yearsInOperationField;
            }
            set {
                this.yearsInOperationField = value;
            }
        }
        
        /// <remarks/>
        public int NumberOfEmployees {
            get {
                return this.numberOfEmployeesField;
            }
            set {
                this.numberOfEmployeesField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyProfile {
            get {
                return this.companyProfileField;
            }
            set {
                this.companyProfileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void UploadDocumentCompletedEventHandler(object sender, UploadDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public APIResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ApproveDocumentCompletedEventHandler(object sender, ApproveDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApproveDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ApproveDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public APIResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void RejectDocumentCompletedEventHandler(object sender, RejectDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RejectDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RejectDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public APIResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetBusinessDetailsCompletedEventHandler(object sender, GetBusinessDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBusinessDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBusinessDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public APIResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CreateBusinessCompletedEventHandler(object sender, CreateBusinessCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateBusinessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateBusinessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CreateDirectorCompletedEventHandler(object sender, CreateDirectorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateDirectorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateDirectorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public APIResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetAllBusinessesCompletedEventHandler(object sender, GetAllBusinessesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllBusinessesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllBusinessesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public APIResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void VerifyUserCredentialsCompletedEventHandler(object sender, VerifyUserCredentialsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifyUserCredentialsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerifyUserCredentialsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void VerifyUserOTPCompletedEventHandler(object sender, VerifyUserOTPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifyUserOTPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerifyUserOTPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VerifyOTPResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VerifyOTPResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CreateDepartmentCompletedEventHandler(object sender, CreateDepartmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateDepartmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateDepartmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CreateRoleCompletedEventHandler(object sender, CreateRoleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateRoleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateRoleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CreateUserCompletedEventHandler(object sender, CreateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetDepartmentsCompletedEventHandler(object sender, GetDepartmentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDepartmentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDepartmentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetRolesCompletedEventHandler(object sender, GetRolesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRolesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRolesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetUsersCompletedEventHandler(object sender, GetUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ValidateNationalIdCompletedEventHandler(object sender, ValidateNationalIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateNationalIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateNationalIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NationalIDValidationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NationalIDValidationResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CheckUserSanctionStatusCompletedEventHandler(object sender, CheckUserSanctionStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckUserSanctionStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckUserSanctionStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SanctionsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SanctionsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetClientDetailsCompletedEventHandler(object sender, GetClientDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClientDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClientDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591